// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.1
// - protoc             v3.21.12
// source: knowledge/v1/knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKnowledgeGetKnowledge = "/api.knowledge.v1.Knowledge/GetKnowledge"

type KnowledgeHTTPServer interface {
	GetKnowledge(context.Context, *GetKnowledgeRequest) (*GetKnowledgeReply, error)
}

func RegisterKnowledgeHTTPServer(s *http.Server, srv KnowledgeHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/knowledge/{id}", _Knowledge_GetKnowledge0_HTTP_Handler(srv))
}

func _Knowledge_GetKnowledge0_HTTP_Handler(srv KnowledgeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKnowledgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeGetKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledge(ctx, req.(*GetKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetKnowledgeReply)
		return ctx.Result(200, reply)
	}
}

type KnowledgeHTTPClient interface {
	GetKnowledge(ctx context.Context, req *GetKnowledgeRequest, opts ...http.CallOption) (rsp *GetKnowledgeReply, err error)
}

type KnowledgeHTTPClientImpl struct {
	cc *http.Client
}

func NewKnowledgeHTTPClient(client *http.Client) KnowledgeHTTPClient {
	return &KnowledgeHTTPClientImpl{client}
}

func (c *KnowledgeHTTPClientImpl) GetKnowledge(ctx context.Context, in *GetKnowledgeRequest, opts ...http.CallOption) (*GetKnowledgeReply, error) {
	var out GetKnowledgeReply
	pattern := "/v1/knowledge/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeGetKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
