// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: knowledge/v1/knowledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKnowledgeRequest) Reset() {
	*x = CreateKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeRequest) ProtoMessage() {}

func (x *CreateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

type CreateKnowledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKnowledgeReply) Reset() {
	*x = CreateKnowledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeReply) ProtoMessage() {}

func (x *CreateKnowledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeReply.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeReply) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

type UpdateKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateKnowledgeRequest) Reset() {
	*x = UpdateKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeRequest) ProtoMessage() {}

func (x *UpdateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

type UpdateKnowledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateKnowledgeReply) Reset() {
	*x = UpdateKnowledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKnowledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeReply) ProtoMessage() {}

func (x *UpdateKnowledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeReply.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeReply) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

type DeleteKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKnowledgeRequest) Reset() {
	*x = DeleteKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeRequest) ProtoMessage() {}

func (x *DeleteKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

type DeleteKnowledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKnowledgeReply) Reset() {
	*x = DeleteKnowledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeReply) ProtoMessage() {}

func (x *DeleteKnowledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeReply.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeReply) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

type GetKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetKnowledgeRequest) Reset() {
	*x = GetKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeRequest) ProtoMessage() {}

func (x *GetKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *GetKnowledgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetKnowledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetKnowledgeReply) Reset() {
	*x = GetKnowledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKnowledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeReply) ProtoMessage() {}

func (x *GetKnowledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeReply.ProtoReflect.Descriptor instead.
func (*GetKnowledgeReply) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *GetKnowledgeReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListKnowledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListKnowledgeRequest) Reset() {
	*x = ListKnowledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeRequest) ProtoMessage() {}

func (x *ListKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

type ListKnowledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListKnowledgeReply) Reset() {
	*x = ListKnowledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeReply) ProtoMessage() {}

func (x *ListKnowledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeReply.ProtoReflect.Descriptor instead.
func (*ListKnowledgeReply) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

var File_knowledge_v1_knowledge_proto protoreflect.FileDescriptor

var file_knowledge_v1_knowledge_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x91,
	0x04, 0x0a, 0x09, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x63, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12,
	0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x63, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x76, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x25, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12,
	0x12, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x5d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x47, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x6d, 0x2f, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_knowledge_v1_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_v1_knowledge_proto_rawDescData = file_knowledge_v1_knowledge_proto_rawDesc
)

func file_knowledge_v1_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(file_knowledge_v1_knowledge_proto_rawDescData)
	})
	return file_knowledge_v1_knowledge_proto_rawDescData
}

var file_knowledge_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_knowledge_v1_knowledge_proto_goTypes = []interface{}{
	(*CreateKnowledgeRequest)(nil), // 0: api.knowledge.v1.CreateKnowledgeRequest
	(*CreateKnowledgeReply)(nil),   // 1: api.knowledge.v1.CreateKnowledgeReply
	(*UpdateKnowledgeRequest)(nil), // 2: api.knowledge.v1.UpdateKnowledgeRequest
	(*UpdateKnowledgeReply)(nil),   // 3: api.knowledge.v1.UpdateKnowledgeReply
	(*DeleteKnowledgeRequest)(nil), // 4: api.knowledge.v1.DeleteKnowledgeRequest
	(*DeleteKnowledgeReply)(nil),   // 5: api.knowledge.v1.DeleteKnowledgeReply
	(*GetKnowledgeRequest)(nil),    // 6: api.knowledge.v1.GetKnowledgeRequest
	(*GetKnowledgeReply)(nil),      // 7: api.knowledge.v1.GetKnowledgeReply
	(*ListKnowledgeRequest)(nil),   // 8: api.knowledge.v1.ListKnowledgeRequest
	(*ListKnowledgeReply)(nil),     // 9: api.knowledge.v1.ListKnowledgeReply
}
var file_knowledge_v1_knowledge_proto_depIdxs = []int32{
	0, // 0: api.knowledge.v1.Knowledge.CreateKnowledge:input_type -> api.knowledge.v1.CreateKnowledgeRequest
	2, // 1: api.knowledge.v1.Knowledge.UpdateKnowledge:input_type -> api.knowledge.v1.UpdateKnowledgeRequest
	4, // 2: api.knowledge.v1.Knowledge.DeleteKnowledge:input_type -> api.knowledge.v1.DeleteKnowledgeRequest
	6, // 3: api.knowledge.v1.Knowledge.GetKnowledge:input_type -> api.knowledge.v1.GetKnowledgeRequest
	8, // 4: api.knowledge.v1.Knowledge.ListKnowledge:input_type -> api.knowledge.v1.ListKnowledgeRequest
	1, // 5: api.knowledge.v1.Knowledge.CreateKnowledge:output_type -> api.knowledge.v1.CreateKnowledgeReply
	3, // 6: api.knowledge.v1.Knowledge.UpdateKnowledge:output_type -> api.knowledge.v1.UpdateKnowledgeReply
	5, // 7: api.knowledge.v1.Knowledge.DeleteKnowledge:output_type -> api.knowledge.v1.DeleteKnowledgeReply
	7, // 8: api.knowledge.v1.Knowledge.GetKnowledge:output_type -> api.knowledge.v1.GetKnowledgeReply
	9, // 9: api.knowledge.v1.Knowledge.ListKnowledge:output_type -> api.knowledge.v1.ListKnowledgeReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_knowledge_v1_knowledge_proto_init() }
func file_knowledge_v1_knowledge_proto_init() {
	if File_knowledge_v1_knowledge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knowledge_v1_knowledge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnowledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKnowledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKnowledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKnowledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKnowledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_v1_knowledge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKnowledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knowledge_v1_knowledge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_knowledge_v1_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_v1_knowledge_proto = out.File
	file_knowledge_v1_knowledge_proto_rawDesc = nil
	file_knowledge_v1_knowledge_proto_goTypes = nil
	file_knowledge_v1_knowledge_proto_depIdxs = nil
}
